name: ✨- Nueva Función (Feature)

on:
  workflow_dispatch:
    inputs:
      issue_label:
        description: 'Selecciona la etiqueta de la Issue a procesar'
        required: true
        type: choice
        default: 'Nueva-Funcion'
        options:
        - 'Cliente-Nuevo'
        - 'Cliente-Existente' 
        - 'Consulta'
        - 'Mejora'
        - 'Bugfix'
        # Solo se ejecuta si coincide con esta etiqueta
        - 'Nueva-Funcion'

jobs:
  triage_nueva_funcion:
    # Se ejecuta solo si la entrada del usuario es 'Nueva-Funcion'
    if: github.event.inputs.issue_label == 'Nueva-Funcion'
    
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Simular Reacción - Roadmapping y Estimación
        run: |
          echo "========================================================================"
          echo "::notice file=PLANIFICACION.md,title=Asignación (Nueva Feature)::Se ha procesado manualmente una solicitud de nueva funcionalidad."
          echo "::warning title=ACCIÓN REQUERIDA (PRODUCT OWNER)::Iniciar el proceso de **estimación**, definición de requerimientos y Roadmapping. Asignar al Product Owner (PO)."
          echo "Etiqueta Seleccionada: ${{ github.event.inputs.issue_label }}"
          echo "========================================================================"